export const UPDATE_FIELD = 'UPDATE_FIELD'
export const UPDATE_FIRST_CLICKED_ITEM_ID = 'UPDATE_FIRST_CLICKED_ITEM_ID'
export const UPDATE_CURRENT_ROUND = 'UPDATE_CURRENT_ROUND'
export const SET_FIELD_SIZE = 'SET_FIELD_SIZE'
export const SET_NUMBER_VARIANTS = 'SET_NUMBER_VARIANTS'
export const SET_NUMBER_ROUNDS = 'SET_NUMBER_ROUNDS'

export const TRANSITION_DELAY = 700
